### ISSUE TITLE
Auto Re-Run?

### ISSUE THREAD

**Issue by advantipro-gmbh** [mnpopcenter/gas-change-ownership#2]
Hi, and thanks so much for this script!

It sounds like you have a far more monstrous collection of files than we have, but when I run the `runCleanup` function, by the time it has completed "Visiting" all of our files, we get about 7 file updated before "Exceeded maximum execution time"...

Other than manually re-running and re-running and re-running, any ideas on getting this to auto re-run, until all files & folders in the `parentFolder` are updated?

Thanks in advance, and thanks again,
Atg

**Comment by franfabrizio** [comment]
You could use a time-driven Google Apps Scripts trigger to periodically re-run your script (though you may hit API limits, not sure). Having said that, this is work from four years ago that I haven't looked at since. Today, we'd probably migrate everything and have the team work off of a Google Shared Drive, which largely avoids the person-leaves-but-still-owns-docs problem in the first place, if that simplified permissions model was sufficient.

**Comment by advantipro-gmbh** [comment]
Thanks a lot, appreciate the help!
